name = "garage-brain"
compatibility_date = "2025-04-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "garage-brain-db"
database_id = "dd618ed7-b66d-4e8d-91f6-cfe1c2b93df7"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "garage-brain-storage"

[[kv_namespaces]]
binding = "CACHE"
id = "73fdc31ea40a42318eff5b307a45f8d8"

[ai]
binding = "AI"
