// Seed data — hardcoded vehicles/projects for local dev and empty-DB fallback.
// Once D1 is populated, this file is only used as a reference.

export const SEED_VEHICLES = [
  {
    id: "leaf-2013",
    year: 2013,
    make: "Nissan",
    model: "Leaf SL",
    color: "#3b82f6",
    bolt_pattern: "5x114.3",
    obd_protocol: "CAN 11-bit 500k",
    icon: "⚡",
    notes: "HVAC blower dead. Blower transistor replaced fan already.",
    projects: [
      {
        id: "leaf-blower",
        vehicle_id: "leaf-2013",
        title: "HVAC Blower Fix",
        status: "active",
        created_at: "2025-01-15",
        updated_at: "2025-01-15",
        module: "repair",
        fsmSections: ["HVAC — Blower Motor", "HVAC — Wiring Diagram"],
        notes: "Replaced fan motor, still dead. Suspect blower motor resistor/transistor. Located passenger footwell, accessible without full dash pull. Have replacement part on hand.",
        steps: [
          { text: "Verify 12V at blower connector with ignition on", done: false },
          { text: "Check blower transistor connector for power & signal", done: false },
          { text: "Test transistor output to blower motor", done: false },
          { text: "If no output → replace transistor (passenger footwell, 2 screws)", done: false },
          { text: "Verify all fan speeds working", done: false },
        ],
        parts: [{ name: "Blower motor transistor", status: "on-hand", part_number: "27761-3SB0A" }],
        tools: [
          { name: "Multimeter", have: true },
          { name: "Test light", have: true },
          { name: "Phillips #2 screwdriver", have: true },
          { name: "Trim removal tool", have: false, note: "For lower dash panel clips — or just be gentle" },
          { name: "10mm socket", have: true, note: "If you can find it" },
        ],
        troubleshooting: {
          symptom: "HVAC blower does not work on any speed",
          known: [
            { fact: "Blower motor replaced — still dead", eliminates: "Motor failure / seized / burned" },
            { fact: "All other electrical works fine", eliminates: "Main fuse / ignition circuit" },
          ],
          currentStep: 0,
          steps: [
            {
              id: "check-fuse",
              instruction: "Check fuse #33 (30A) in IPDM (under-hood fuse box)",
              detail: "This is the main blower motor fuse. Pull it and inspect visually, or test continuity with your multimeter.",
              fsmRef: "BL-8, PG-42",
              expect: "Fuse intact / continuity",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-blower-relay",
              instruction: "Check blower motor relay in IPDM",
              detail: "Swap with another identical relay in the box to test. Listen for click when turning fan switch on.",
              fsmRef: "BL-10",
              expect: "Relay clicks, or works with known-good swap",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-power-at-transistor",
              instruction: "Check 12V at blower transistor connector (passenger footwell)",
              detail: "3-pin connector on the transistor unit. With ignition ON and fan switch on, you should see 12V on the power input pin. Probe with multimeter — black lead to chassis ground.",
              fsmRef: "BL-12, EC-48",
              expect: "12V present at power pin",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-signal-at-transistor",
              instruction: "Check control signal at transistor connector",
              detail: "The BCM sends a variable signal to the transistor to control fan speed. With fan switch on different speeds, you should see varying voltage on the signal pin (typically 0-5V PWM).",
              fsmRef: "BL-12, EC-50",
              expect: "Voltage changes when fan speed selector is moved",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-transistor-output",
              instruction: "Check transistor output to blower motor",
              detail: "Measure voltage on the output side going to the motor. If you have power in and signal in but no output — transistor is dead. This is the most likely failure point since you already replaced the motor.",
              fsmRef: "BL-14",
              expect: "Voltage present, varies with speed setting",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "replace-transistor",
              instruction: "Replace blower motor transistor",
              detail: "2 screws hold it in. Passenger footwell, tucked up behind the lower dash panel on the HVAC housing. You should be able to reach it without pulling the dash — just remove the lower kick panel (2 clips + 1 screw). Part is on hand: 27761-3SB0A.",
              fsmRef: "BL-16",
              expect: "Blower works on all speeds after replacement",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "verify-all-speeds",
              instruction: "Verify all fan speeds 1-4 and defrost mode",
              detail: "Turn on the car, cycle through every fan speed. Let it run for a few minutes at max speed to confirm it doesn't cut out. Test defrost mode specifically since that's what made winter hell.",
              fsmRef: "BL-4",
              expect: "All speeds work, defrost blows strong",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
          ],
        },
      },
      {
        id: "leaf-alignment",
        vehicle_id: "leaf-2013",
        title: "4-Wheel Alignment",
        status: "planned",
        created_at: "2026-04-11",
        module: "alignment",
        fsmSections: ["FSU — Front Suspension", "RSU — Rear Suspension"],
        notes: "Front tires fucked from running without alignment after suspension work. Front camber/caster NOT adjustable, toe only. Rear toe + camber adjustable.",
        steps: [],
        parts: [],
        tools: [
          { name: "Printed checkerboard targets", have: false },
          { name: "3D printed wheel mount (5x114.3)", have: false },
          { name: "19mm wrench (tie rod jam nut)", have: true },
          { name: "Tape measure", have: true },
        ],
      },
    ],
  },
  {
    id: "golf-2003",
    year: 2003,
    make: "VW",
    model: "Golf",
    color: "#22c55e",
    bolt_pattern: "5x100",
    obd_protocol: "CAN / K-line",
    icon: "🟢",
    notes: "Won't start. Suspect fuel pump.",
    projects: [
      {
        id: "golf-nostart",
        vehicle_id: "golf-2003",
        title: "No-Start Diagnosis",
        status: "active",
        created_at: "2026-03-01",
        module: "diagnostics",
        fsmSections: ["Fuel Supply — Fuel Pump", "Engine Mgmt — Starting System", "Wiring — Fuel Pump Circuit"],
        notes: "Engine cranks, won't fire. Need to verify spark, fuel pressure, and immobilizer status. Check fuel pump relay first (common Mk4 failure).",
        steps: [
          { text: "Turn key to ON — listen for fuel pump prime (2sec hum from rear)", done: false },
          { text: "If no prime → check fuel pump relay (position 409 in relay panel)", done: false },
          { text: "Check fuse #28 (15A) fuel pump", done: false },
          { text: "If relay/fuse OK → test power at fuel pump connector (under rear seat)", done: false },
          { text: "If power OK → fuel pump is dead, replace", done: false },
          { text: "If no power → trace wiring, check grounds", done: false },
          { text: "Also verify: spark present at plugs, immobilizer light behavior", done: false },
        ],
        parts: [],
        tools: [
          { name: "Multimeter", have: true },
          { name: "Test light", have: true },
          { name: "Fuel pressure gauge", have: false, note: "Schrader valve on fuel rail — borrow or rent from AutoZone" },
          { name: "Spark tester", have: false, note: "Inline — cheap, worth having" },
          { name: "Relay puller or needle nose pliers", have: true },
          { name: "Spare fuel pump relay (for swap test)", have: false, note: "Same relay used in multiple spots, swap from another position to test" },
        ],
        troubleshooting: {
          symptom: "Engine cranks but will not start",
          known: [
            { fact: "Engine cranks at normal speed", eliminates: "Starter / battery / ignition switch" },
          ],
          currentStep: 0,
          steps: [
            {
              id: "listen-fuel-pump",
              instruction: "Turn key to ON (not start) — listen for fuel pump prime",
              detail: "Sit in the car, windows up, quiet. Turn key to ON position. You should hear a 2-second hum/whine from the rear of the car. This is the fuel pump pressurizing the rail. No sound = pump isn't running.",
              fsmRef: "Fuel Supply 20-1",
              expect: "2-second hum from rear of car",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-fuel-pump-relay",
              instruction: "Locate and test fuel pump relay — position 409 in relay panel",
              detail: "Under dash, driver side relay panel. Position 409. Pull it, inspect contacts for burning. Swap with an identical relay from another position (horn, AC, etc.) and re-test fuel pump prime. Common Mk4 failure — relay contacts burn out.",
              fsmRef: "Fuel Supply 20-4, Relay Panel 97-3",
              expect: "Fuel pump primes with swapped relay",
              testType: "choice",
              choices: [
                { label: "Pump primes with swapped relay", next: "confirm-relay-fix", color: "#4ade80" },
                { label: "Still no prime with swapped relay", next: "check-fuel-fuse", color: "#f87171" },
                { label: "Original relay was fine (pump primed in step 1)", next: "check-fuel-pressure", color: "#818cf8" },
              ],
              result: null, testedAt: null, note: "",
            },
            {
              id: "confirm-relay-fix",
              instruction: "Order a new relay — that was your problem",
              detail: "Common VW Mk4 failure. The relay is cheap (~$8). Order the correct one for position 409. In the meantime the swapped relay will work fine.",
              fsmRef: "Fuel Supply 20-4",
              expect: "Car starts",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-fuel-fuse",
              instruction: "Check fuse #28 (15A) — fuel pump circuit",
              detail: "In the under-dash fuse panel. Pull and inspect, or test continuity. If blown, replace and test. If it blows again immediately, you have a short in the fuel pump wiring.",
              fsmRef: "Fuse Panel 97-5",
              expect: "Fuse intact",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-pump-power",
              instruction: "Test power at fuel pump connector (under rear seat)",
              detail: "Pull up the rear seat bottom (clips at front, pull up firmly). You'll see an access panel. Open it to find the fuel pump connector. With key ON, probe for 12V.",
              fsmRef: "Fuel Supply 20-8, Wiring 97-40",
              expect: "12V at fuel pump connector with key ON",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-fuel-pressure",
              instruction: "Check fuel pressure at rail",
              detail: "Connect fuel pressure gauge to Schrader valve on fuel rail. Key ON, engine off — should see ~55-60 PSI (3.8-4.1 bar). Rent gauge from AutoZone free.",
              fsmRef: "Fuel Supply 20-12",
              expect: "55-60 PSI / 3.8-4.1 bar",
              testType: "measurement",
              unit: "PSI",
              specMin: 50, specMax: 65,
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-spark",
              instruction: "Check for spark at plugs",
              detail: "Pull a coil pack connector, plug in an inline spark tester, crank engine. You should see a bright blue/white spark. Test multiple cylinders.",
              fsmRef: "Ignition 28-1",
              expect: "Strong blue/white spark visible",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-immobilizer",
              instruction: "Check immobilizer light behavior on dash",
              detail: "Key to ON — watch the immobilizer light (car with key icon). Should flash briefly then go OFF.",
              fsmRef: "Immobilizer 96-1",
              expect: "Light flashes then goes off within 2-3 seconds",
              testType: "choice",
              choices: [
                { label: "Light goes off (immobilizer OK)", next: "check-crank-sensor", color: "#4ade80" },
                { label: "Light stays on / keeps flashing", next: "immobilizer-issue", color: "#f87171" },
              ],
              result: null, testedAt: null, note: "",
            },
            {
              id: "immobilizer-issue",
              instruction: "Immobilizer is preventing start",
              detail: "Try your spare key first. If spare works — original key transponder is dead. If neither key works — needs VCDS/VAG-COM to re-adapt keys.",
              fsmRef: "Immobilizer 96-4",
              expect: "Spare key starts the car, or VCDS re-adaptation needed",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
            {
              id: "check-crank-sensor",
              instruction: "Check crankshaft position sensor",
              detail: "If you have fuel AND no spark on any cylinder, the crank position sensor is suspect. Located on the bell housing, driver side. Resistance should be 700-1000 ohms.",
              fsmRef: "Engine Sensors 24-12",
              expect: "Resistance 700-1000 ohms, connector clean",
              testType: "pass_fail",
              result: null, testedAt: null, note: "",
            },
          ],
        },
      },
    ],
  },
  {
    id: "ram-2000",
    year: 2000,
    make: "Dodge",
    model: "Ram 2500 Cummins",
    color: "#ef4444",
    bolt_pattern: "8x165.1",
    obd_protocol: "J1850 / CAN",
    icon: "🔴",
    notes: "47RE rebuilt but valve body not installed. 3 years. Don't tell anyone.",
    projects: [
      {
        id: "ram-47re",
        vehicle_id: "ram-2000",
        title: "47RE Valve Body Install",
        status: "active",
        created_at: "2023-06-01",
        updated_at: "2023-06-15",
        module: "repair",
        fsmSections: ["21 — Transmission", "21 — Valve Body", "21 — Fluid & Adjustments"],
        notes: "Trans rebuilt with shift improvement kits + HD components. Torque converter refurbed and installed. VALVE BODY STILL OUT.",
        steps: [
          { text: "Locate valve body + shift kit components (garage shelf?)", done: false },
          { text: "Clean valve body mating surface on trans case", done: false },
          { text: "Install valve body with shift kit modifications per kit instructions", done: false },
          { text: "Torque VB bolts to spec (sequence matters)", done: false },
          { text: "Install new filter + gasket on pan", done: false },
          { text: "Adjust front band (kickdown) — back off, torque 72 in-lb, back off, 2.5 turns", done: false },
          { text: "Adjust rear band — back off, torque 72 in-lb, back off, 4 turns", done: false },
          { text: "Install pan, fill with ATF+4 (approx 4qt initial)", done: false },
          { text: "Start engine, shift through gears, check level, top off", done: false },
          { text: "Road test — check shift points, line pressure, temp", done: false },
        ],
        parts: [
          { name: "Valve body assembly (rebuilt w/ shift kit)", status: "on-hand" },
          { name: "Trans filter + gasket kit", status: "need" },
          { name: "ATF+4 (12qt)", status: "need" },
        ],
        tools: [
          { name: "Inch-pound torque wrench", have: true, note: "Critical for band adjustments — 72 in-lb" },
          { name: "Ft-lb torque wrench", have: true },
          { name: "T-handle ratchet (for VB bolts)", have: true },
          { name: "Transmission funnel w/ long neck", have: false, note: "Fill tube is awkward on the 2nd gen" },
          { name: "Drain pan (big — 12qt+)", have: true },
          { name: "Band adjustment tool / socket", have: true },
          { name: "Gasket scraper / razor blade", have: true },
          { name: "RTV sealant", have: false, note: "For pan if not using gasket" },
          { name: "OBD2 scanner (for trans temp monitoring)", have: true, note: "Use the Foxwell — it reads trans PIDs" },
        ],
      },
    ],
  },
  {
    id: "qx60-2013",
    year: 2013,
    make: "Infiniti",
    model: "QX60",
    color: "#a855f7",
    bolt_pattern: "5x114.3",
    obd_protocol: "CAN 11-bit 500k",
    icon: "🟣",
    notes: "Buddy's car. Needs alignment. Same bolt pattern as Leaf — shares mount plate.",
    projects: [
      {
        id: "qx60-alignment",
        vehicle_id: "qx60-2013",
        title: "4-Wheel Alignment",
        status: "planned",
        module: "alignment",
        created_at: "2026-04-11",
        fsmSections: [],
        notes: "Find FSM. Same 5x114.3 bolt pattern as Leaf, same alignment target hardware works.",
        steps: [],
        parts: [],
        tools: [
          { name: "Printed checkerboard targets", have: false, note: "Same as Leaf set" },
          { name: "3D printed wheel mount (5x114.3)", have: false, note: "Shares with Leaf mount" },
        ],
      },
    ],
  },
];
